build:
  nodes:
    coverage-tests:
      tests:
        override:
          - command: phpunit --coverage-clover=coverage.xml
            coverage:
              file: coverage.xml
              format: php-clover
